### PR TITLE
getting class name using java method rather than str

### PR DESCRIPTION
**Pull request by firthh**

### CODE REVIEW

**Comment by bmabey** [comment]
Thanks for being so responsive on this @firthh. I've released `v3.0.2`. /cc @cap10morgan

**Comment by firthh** [comment]
No worries, I'm more than happy to be added to the collaborators for this project if it makes your life easier

**Comment by cap10morgan** [comment]
Awesome, thanks @firthh & @bmabey.

**Comment by bmabey** [comment]
@firthh Thanks for the offer. I've added you as a contributor on github. I don't see a way of doing the same on clojars though.

**Comment by firthh** [comment]
@bmabey Thanks :)
I think if you go to here - https://clojars.org/groups/clj-airbrake you can add new members?

**Comment by bmabey** [comment]
Ah, there it is. Okay, I added you there as well. Thanks!

**Pull request merged**
